version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: /bin/sh -c "php -S 0.0.0.0:80"
    ports:
      - 6969:80